--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksctl-test
  region: us-east-1

nodeGroups:
  - name: ng1-public
    instanceType: t3.micro
    desiredCapacity: 1
  
managedNodeGroups:
  - name: ng2-managed
    instanceType: t3.micro
    minSize: 1
    maxSize: 1
    desiredCapacity: 1  