apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostname-v1
      version: v1
  template:
    metadata:
      labels:
        app: hostname-v1
        version: v1
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: '9901'
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - image: rstarmer/hostname:v1
        imagePullPolicy: Always
        name: hostname
        resources:
          limits:
            cpu: 256m
            memory: 128Mi
      - name: envoy
        image: opsani/envoy-sidecar:latest
        imagePullPolicy: Always
        env:
        - name: SERVICE_PORT
          value: "80"
        - name: LISTEN_PORT
          value: "8080"
        - name: METRICS_PORT
          value: "9901"
        ports:
          - containerPort: 8080
            name: service       # service listener provided by Envoy proxy
          - containerPort: 9901
            name: metrics       # metrics provided by Envoy
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 125m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hostname-v1
  name: hostname-v1
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hostname-v1
